//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wox.Plugin.Onenote.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wox.Plugin.Onenote.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;one:Notebooks xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot;&gt;
        ///  &lt;one:Notebook name=&quot;notebook1&quot; nickname=&quot;notebook1&quot; ID=&quot;{9F1B9187-5FB0-4E92-8631-0E6521CC9437}{1}{B0}&quot; lastModifiedTime=&quot;2019-11-07T19:43:03.000Z&quot; color=&quot;#8AA8E4&quot;&gt;
        ///    &lt;one:Section name=&quot;Section 1&quot; ID=&quot;{6D837AA3-08A0-F3A7-349D-EDC2654A5900}{1}{B0}&quot; path=&quot;c:/temp/place/New Section 2.one&quot; lastModifiedTime=&quot;2019-11-03T07:08:06.000Z&quot; color=&quot;#8AA8E4&quot;&gt;
        ///      &lt;one:Page ID=&quot;{6D837AA3-08A0-F3A7-349D-EDC2654A5900}{1}{E2017269343 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicResult {
            get {
                return ResourceManager.GetString("BasicResult", resourceCulture);
            }
        }
    }
}
