//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wox.Plugin.Onenote.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wox.Plugin.Onenote.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;one:Notebooks xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2013/onenote&quot;&gt;
        ///  &lt;one:Notebook name=&quot;My Notebook&quot; nickname=&quot;My Notebook&quot; ID=&quot;{AFF6CE2D-8188-45C8-9829-6FAC1CB66023}{1}{B0}&quot; path=&quot;C:\Users\atepper\Documents\OneNote Notebooks\My Notebook&quot; lastModifiedTime=&quot;2019-11-07T10:49:38.000Z&quot; color=&quot;#B7C997&quot;&gt;
        ///    &lt;one:Section name=&quot;Quick Notes&quot; ID=&quot;{54DADC52-B1C5-02DF-0F93-7E8525D86438}{1}{B0}&quot; path=&quot;C:\Users\atepper\Documents\OneNote Notebooks\My Notebook\Quick Notes.one&quot; lastModifiedTime=&quot;2019-1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TodayStringResult {
            get {
                return ResourceManager.GetString("TodayStringResult", resourceCulture);
            }
        }
    }
}
